services:
  app:
    build: .
    container_name: be_analytic_ETL
    depends_on:
      - db
    env_file: 
      - token.env
    command: sh -c "python main.py && python connect_postgre.py"

  db:
    image: postgres:17.5-bookworm
    container_name: app_postgres
    restart: unless-stopped
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "12345"
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: be_analytic_pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data: